/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class CRobot */

#ifndef _Included_CRobot
#define _Included_CRobot
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     CRobot
 * Method:    move
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_CRobot_move
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     CRobot
 * Method:    move_with_radio
 * Signature: (IID)Z
 */
JNIEXPORT jboolean JNICALL Java_CRobot_move_1with_1radio
  (JNIEnv *, jobject, jint, jint, jdouble);

/*
 * Class:     CRobot
 * Method:    click
 * Signature: (IZ)Z
 */
JNIEXPORT jboolean JNICALL Java_CRobot_click
  (JNIEnv *, jobject, jint, jboolean);

#ifdef __cplusplus
}
#endif
#endif
